apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: feature-flags-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: padmanabhan1/todo-backend:latest
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SECRET_KEY
            - name: ALGORITHM
              value: "HS256"
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: "30"
            - name: MONGO_URL
              value: "mongodb://mongodb:27017/fastapi_db"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: feature-flags-demo
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-loadbalancer
  namespace: feature-flags-demo
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 8000
